//! Kinds of rework the arbiter can request. Six variants:
//! `Revise` (same worker + directive), `Reassign` (fresh worker,
//! optional vendor swap), `Split` (replace task with sub-tasks),
//! `Narrow` (scope_paths overlay), `Rebrief` (task title overlay),
//! `MarkUnachievable` (escalate with rationale).
//!
//! Externally tagged: `#[serde(tag = "kind", rename_all = "snake_case")]`.
//! Wire form examples:
//!
//! ```json
//! { "kind": "revise", "directive": "address the TODO" }
//! { "kind": "reassign", "from_worker": "mock-1", "to_vendor": "codex" }
//! { "kind": "split", "sub_tasks": [{"index": 0, "title": "..."}] }
//! { "kind": "narrow", "reduced_scope": ["src/lib.rs"] }
//! { "kind": "rebrief", "new_brief": "implement only the parser" }
//! { "kind": "mark_unachievable", "rationale": "..." }
//! ```

use event_schema::Vendor;
use serde::{Deserialize, Serialize};
use specta::Type;
use std::path::PathBuf;

use crate::mission_event::TaskDescriptor;

/// Type alias matching `crate::mission::WorkerId` without coupling this
/// wire-facing module to the mission runtime.
pub type WorkerId = String;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ReworkKind {
    /// Re-run the same worker with a directive. Cheapest. Arbiter's
    /// default when the supervisor hasn't picked something specific.
    Revise { directive: String },

    /// Tear down the failing worker, spawn a fresh one. Optional
    /// vendor swap. Use when the worker is stuck in a loop / lost
    /// context, or the vendor is a poor match for the task. `from_worker`
    /// is the worker_id being torn down; fresh id is generated by
    /// mission loop (`{base}-r{attempt}`). `to_vendor: None` keeps
    /// current vendor.
    Reassign {
        from_worker: WorkerId,
        to_vendor: Option<Vendor>,
    },

    /// Replace the current task with N smaller sub-tasks. Descriptor indices
    /// are local to the replacement; the mission loop remaps them into the
    /// live DAG after the current task.
    Split { sub_tasks: Vec<TaskDescriptor> },

    /// Re-run with a constrained scope_paths overlay. Applies to the
    /// next pass only. Empty means "no constraint" (Revise-equivalent).
    /// The dispatcher enforces this through the file ACL before integration.
    Narrow { reduced_scope: Vec<PathBuf> },

    /// Re-run with a fully replaced brief. Used in place of
    /// `task.title` for the next pass.
    Rebrief { new_brief: String },

    /// Supervisor declares the task cannot be automated to passing. The
    /// reviewable workspace is retained and the mission advances to Attention.
    MarkUnachievable { rationale: String },
}

impl ReworkKind {
    /// String discriminant for log lines and JSON-sniffing in
    /// visibility routing. Matches the wire `kind` field.
    pub fn discriminant(&self) -> &'static str {
        match self {
            Self::Revise { .. } => "revise",
            Self::Reassign { .. } => "reassign",
            Self::Split { .. } => "split",
            Self::Narrow { .. } => "narrow",
            Self::Rebrief { .. } => "rebrief",
            Self::MarkUnachievable { .. } => "mark_unachievable",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip(r: ReworkKind) {
        let json = serde_json::to_string(&r).unwrap();
        let back: ReworkKind = serde_json::from_str(&json).unwrap();
        assert_eq!(r, back, "round-trip mismatch: {json}");
    }

    #[test]
    fn revise_round_trips() {
        round_trip(ReworkKind::Revise {
            directive: "fix the TODO".into(),
        });
    }

    #[test]
    fn reassign_with_vendor_round_trips() {
        round_trip(ReworkKind::Reassign {
            from_worker: "mock-1".into(),
            to_vendor: Some(Vendor::Codex),
        });
    }

    #[test]
    fn reassign_without_vendor_round_trips() {
        round_trip(ReworkKind::Reassign {
            from_worker: "mock-2".into(),
            to_vendor: None,
        });
    }

    #[test]
    fn split_round_trips() {
        round_trip(ReworkKind::Split {
            sub_tasks: vec![
                TaskDescriptor {
                    index: 0,
                    title: "Add parser".into(),
                    ..Default::default()
                },
                TaskDescriptor {
                    index: 1,
                    title: "Add tests".into(),
                    ..Default::default()
                },
            ],
        });
    }

    #[test]
    fn split_empty_round_trips() {
        round_trip(ReworkKind::Split { sub_tasks: vec![] });
    }

    #[test]
    fn narrow_round_trips() {
        round_trip(ReworkKind::Narrow {
            reduced_scope: vec![PathBuf::from("src/lib.rs")],
        });
    }

    #[test]
    fn narrow_empty_round_trips() {
        round_trip(ReworkKind::Narrow {
            reduced_scope: vec![],
        });
    }

    #[test]
    fn rebrief_round_trips() {
        round_trip(ReworkKind::Rebrief {
            new_brief: "implement only the parser, no tests yet".into(),
        });
    }

    #[test]
    fn mark_unachievable_round_trips() {
        round_trip(ReworkKind::MarkUnachievable {
            rationale: "task requires manual code review of legacy fork".into(),
        });
    }

    #[test]
    fn discriminant_matches_wire_kind() {
        assert_eq!(
            ReworkKind::Revise {
                directive: String::new()
            }
            .discriminant(),
            "revise"
        );
        assert_eq!(
            ReworkKind::Reassign {
                from_worker: "x".into(),
                to_vendor: None,
            }
            .discriminant(),
            "reassign"
        );
        assert_eq!(
            ReworkKind::Split { sub_tasks: vec![] }.discriminant(),
            "split"
        );
        assert_eq!(
            ReworkKind::Narrow {
                reduced_scope: vec![]
            }
            .discriminant(),
            "narrow"
        );
        assert_eq!(
            ReworkKind::Rebrief {
                new_brief: String::new()
            }
            .discriminant(),
            "rebrief"
        );
        assert_eq!(
            ReworkKind::MarkUnachievable {
                rationale: String::new(),
            }
            .discriminant(),
            "mark_unachievable"
        );
    }

    #[test]
    fn discriminant_round_trips_via_json_sniff() {
        for variant in [
            ReworkKind::Revise {
                directive: "x".into(),
            },
            ReworkKind::Reassign {
                from_worker: "x".into(),
                to_vendor: None,
            },
            ReworkKind::Split { sub_tasks: vec![] },
            ReworkKind::Narrow {
                reduced_scope: vec![],
            },
            ReworkKind::Rebrief {
                new_brief: "x".into(),
            },
            ReworkKind::MarkUnachievable {
                rationale: "x".into(),
            },
        ] {
            let json = serde_json::to_string(&variant).unwrap();
            let needle = format!("\"kind\":\"{}\"", variant.discriminant());
            assert!(json.contains(&needle), "expected {needle} in {json}");
        }
    }
}
