// @ts-nocheck
// Auto-generated by tauri-specta. Do not edit.
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<HealthDto> {
    return await TAURI_INVOKE("health_check");
},
/**
 * P4 — Durable startup state. Polling observes both success and failure, so
 * neither result depends on attaching an event listener early enough.
 */
async startupStatus() : Promise<StartupStatusDto> {
    return await TAURI_INVOKE("startup_status");
},
async startMockWorker(script: string, speed: number | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_mock_worker", { script, speed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startClaudeWorker(prompt: string, cwd: string, maxTurns: number | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_claude_worker", { prompt, cwd, maxTurns }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCodexWorker(prompt: string, cwd: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_codex_worker", { prompt, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startGeminiWorker(prompt: string, cwd: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_gemini_worker", { prompt, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWorker(workerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_worker", { workerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Step 25 — continue a worker with a follow-up prompt. Resumes the
 * worker's CLI session if supported, or returns an error if resume is
 * not available or the worker is still running.
 */
async continueWorker(workerId: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_worker", { workerId, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Step 25 — retry a worker with its last prompt. Re-runs the original
 * prompt against the worker's resumed CLI session.
 */
async retryWorker(workerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_worker", { workerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Batch 2 — get unified diff for a worker's worktree.
 * Runs `git diff --unified=3` in the worker's cwd and returns the output.
 * Returns empty string if git is not available or the cwd is not a git repo.
 */
async getWorkerDiff(workerId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worker_diff", { workerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecentWorkers(limit: number | null) : Promise<Result<WorkerInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recent_workers", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkerInfo(workerId: string) : Promise<Result<WorkerInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worker_info", { workerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchWorkerModel(workerId: string, model: string) : Promise<Result<WorkerModelSwitchDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_worker_model", { workerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replayWorkerEventsPage(workerId: string, afterSeq: number | null, limit: number) : Promise<Result<Event[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replay_worker_events_page", { workerId, afterSeq, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettings() : Promise<AppSettingsDto> {
    return await TAURI_INVOKE("app_settings");
},
async checkCliAuth() : Promise<CliAuthStatusDto[]> {
    return await TAURI_INVOKE("check_cli_auth");
},
async openCliLogin(vendor: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_cli_login", { vendor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openCliAuthDocs(vendor: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_cli_auth_docs", { vendor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlaybooks() : Promise<Result<StoredPlaybook[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_playbooks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePlaybook(id: string, json: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_playbook", { id, json }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePlaybook(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_playbook", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask the native host to choose the destination and then write the generated
 * SVG. The renderer supplies only a suggested filename, never an authorized
 * filesystem path.
 */
async saveMindMapFile(filename: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_mind_map_file", { filename, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a mission. Business routing and lifecycle locking live in
 * `orchestrator::MissionController`; this command only forwards the
 * resulting event stream to Tauri.
 */
async startMission(spec: MissionSpec, cwd: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_mission", { spec, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abort the active mission. Refuses if no mission is active or if
 * it has already terminated.
 */
async abortMission() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_mission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply the user's executable final disposition (Merge / Discard).
 * The reserved Extend wire variant fails closed in the runtime.
 * Blocks until the active mission reaches `CompletePendingMerge`.
 */
async resolveMission(action: ResolveAction) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_mission", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * QC-2: confirm the supervisor's currently-proposed plan. Only
 * valid when the active mission is paused at
 * `PendingPlanApproval` (i.e. it was started with
 * `MissionSpec.confirm_plan == true`). Follows the same
 * lock-discipline as `resolve_mission` so a slow inner await
 * doesn't queue every other IPC call.
 */
async confirmPlan(generation: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_plan", { generation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * QC-2: request a regenerated plan with optional natural-language
 * feedback. Only valid when the active mission is paused at
 * `PendingPlanApproval`.
 */
async regeneratePlan(generation: number, hint: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("regenerate_plan", { generation, hint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * QC-3: reject the proposed plan and abort the mission. Only valid
 * while the active mission is paused at `PendingPlanApproval`.
 * Mirrors the shape of `confirm_plan` / `regenerate_plan`; the
 * orchestrator emits `PlanRejected { generation, reason }` followed
 * by `Aborted { reason }` (with the user's reason embedded).
 */
async rejectPlan(generation: number, reason: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_plan", { generation, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revertMission(missionId: string) : Promise<Result<RevertOutcomeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revert_mission", { missionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove only Vigla-owned Git artifacts retained after an aborted mission.
 * The durable outcome supplies both authorization and repository identity;
 * the caller cannot substitute its current working directory. Git cleanup is
 * idempotent, and completion is recorded only after every cleanup target
 * succeeds, so a crash or database failure can be retried safely.
 */
async cleanupMissionArtifacts(missionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_mission_artifacts", { missionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryPinNote(cwd: string, request: PinNoteRequest) : Promise<Result<PinNoteResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_pin_note", { cwd, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryListNotes(cwd: string, stateFilter: NoteStateFilter | null, limit: number | null) : Promise<Result<MemoryNoteSummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_list_notes", { cwd, stateFilter, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryRecentEventsForMission(cwd: string, missionId: string, limit: number | null) : Promise<Result<MemoryEventDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_recent_events_for_mission", { cwd, missionId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryLatestBundleForMission(cwd: string, missionId: string) : Promise<Result<MemoryBundleDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_latest_bundle_for_mission", { cwd, missionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async missionEventVisibility(event: MissionEventKindDto) : Promise<EventVisibility> {
    return await TAURI_INVOKE("mission_event_visibility", { event });
},
async surfaceInboxNotification(title: string, body: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("surface_inbox_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecentMissions(limit: number) : Promise<Result<MissionHistoryRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recent_missions", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
missionEventDto: MissionEventDto,
workerEvent: WorkerEvent
}>({
missionEventDto: "mission-event-dto",
workerEvent: "worker-event"
})

/** user-defined constants **/

export const SCHEMA_VERSION = "2.0" as const;

/** user-defined types **/

export type AcceptPayload = { audit: AuditReport; summary: string }
/**
 * Per-task pass/fail conditions evaluated post-audit. Each field
 * is optional; an empty `AcceptanceCriteria` reduces to "any
 * arbiter Accept is fine".
 */
export type AcceptanceCriteria = { 
/**
 * Minimum composite audit score for this specific task.
 * `None` falls back to `ArbiterPolicy::quality_min`.
 */
min_audit_overall?: number | null; 
/**
 * If `Some(true)`, the task's audit must include a TestPass
 * sub-score with `failed == 0`. `Some(false)` explicitly
 * allows test failures (e.g. for a docs-only task).
 */
require_tests_pass?: boolean | null; 
/**
 * If `Some(true)`, the task must NOT introduce any new
 * security flags. `Some(false)` is interpreted as "the
 * supervisor has reviewed and accepts the risk".
 */
forbid_new_security_flags?: boolean | null; 
/**
 * Human-readable summary. Surfaced in the inbox card on
 * criteria failure; never used to make a decision.
 */
summary?: string | null }
export type AppSettingsDto = { version: string; db_path: string; configured_repo_root: string | null; mock_harness_path: string; mock_harness_present: boolean; l1_quota_mock_enabled: boolean; claude_present: boolean; codex_present: boolean; gemini_present: boolean; antigravity_present: boolean; kiro_present: boolean; copilot_present: boolean; cli_auth: CliAuthStatusDto[] }
export type ArbiterDecision = ({ kind: "accept" } & AcceptPayload) | { kind: "extend"; rework_kind: ReworkKind; attempts_remaining: number } | { kind: "scrub"; reason: ScrubReason; retained_artifacts: string[]; partial_audit: AuditReport | null } | { kind: "escalate"; bound: AuthorityBound; evidence: EscalationEvidence; suggested_user_action: SuggestedUserAction }
export type Artifact = { kind: ArtifactKind; 
/**
 * Renamed because `ref` is a Rust keyword; the wire name stays
 * `ref`.
 */
ref: string; label?: string | null }
export type ArtifactKind = "file" | "diff" | "report" | "url"
export type AuditReport = { 
/**
 * Composite score in [0.0, 1.0]. Computed by `composite::blend`.
 */
overall: number; test_pass: TestPassScore | null; scope: ScopeScore | null; regression: RegressionScore | null; lint: LintScore | null; security_flags: SecurityFlag[] }
export type AuthorityBound = 
/**
 * Worker touched files outside the declared `scope_paths`.
 */
"scope" | 
/**
 * Snapshot creation, rebase, or integration failed. The pure arbiter
 * cannot probe Git; the mission integration boundary maps those I/O
 * failures to this bound before entering `Attention`.
 */
"reversibility" | 
/**
 * A risk detector tripped (schema migration, mass deletion,
 * secret-touching change, …). Mapped from
 * [`crate::audit::SecurityFlagKind`].
 */
"risk" | 
/**
 * Audit score is below the policy quality floor and rework
 * budget cannot rescue it.
 */
"quality"
/**
 * A bound classification plus the supervisor's free-form note
 * explaining *why* — surfaced in the FE envelope-panel tooltip.
 */
export type BoundFit = { fit: BoundFitKind; note?: string }
/**
 * Per-bound classification of the proposed plan against the
 * user's authority envelope. Three buckets:
 * 
 * - `Within` — the plan fits comfortably under the bound.
 * - `NearLimit` — close enough that an extra rework iteration
 * could push it over.
 * - `Exceeds` — the plan as proposed is past the bound; the
 * `mission_loop` gate forces `PendingPlanApproval` even in
 * Direct mode when any bound reaches this value.
 */
export type BoundFitKind = "within" | "near_limit" | "exceeds"
export type CliAuthState = "ready" | "missing_cli" | "not_logged_in" | "unknown"
export type CliAuthStatusDto = { vendor: string; display_name: string; binary: string; binary_present: boolean; state: CliAuthState; detail: string; login_command: string; docs_url: string }
export type Completion = { summary: string; artifacts?: Artifact[] | null; duration_ms?: number | null }
/**
 * Mission-level "is this done?" verdict assembled after the per-task loop.
 */
export type CompletionVerdict = { 
/**
 * True iff every subtask landed in
 * [`ArbiterDecision::Accept`] rather than any other decision.
 */
all_subtasks_accepted: boolean; 
/**
 * The integrated test-pass score. Sourced from the latest
 * [`crate::mission_event::MissionEventKind::PostIntegrationAuditCompleted`]
 * when present; falls back to the last per-task
 * `AuditCompleted` when no post-integration audit ran.
 * `None` if the mission had no audits at all (degenerate case
 * for missions with zero tasks).
 */
integrated_test_pass: TestPassScore | null; 
/**
 * Residual-risk band derived by [`crate::judgment::risk_band::score_risk`].
 */
residual_risk: RiskBand; 
/**
 * Doc-coverage score in [0.0, 1.0]. v1: ratio of touched
 * files that contain a top-of-file doc-comment block.
 */
doc_coverage: number; 
/**
 * Issues that did not resolve cleanly during the mission.
 * Includes open escalations, recovery attempts, context-budget
 * truncations, and supervisor-scrubbed subtasks.
 */
unresolved_issues: UnresolvedIssue[]; 
/**
 * Derived recommendation: `Accept` if all_subtasks_accepted
 * && residual_risk in {Low,Medium} && no open escalations;
 * `Scrub` otherwise, including residual_risk High.
 */
recommendation: ArbiterDecision }
/**
 * Which compose path produced a memory bundle. Carried on
 * [`MissionEventKind::ContextBundleComposed`] so replay can tell
 * `compose_manual` from `compose_retrieval` without re-deriving
 * it from the surrounding event stream.
 */
export type ComposeSource = "manual" | "retrieval"
export type Cost = { input_tokens: number; output_tokens: number; usd: number; cache_read_tokens?: number | null; cache_write_tokens?: number | null; model?: string | null }
/**
 * Side effects Vigla can surface before/while running a vendor CLI.
 */
export type DeclaredSideEffectKind = "package_install" | "paid_api_call" | "external_mutation" | "network_egress"
export type Dependency = { waiting_on: string[]; reason: string; since?: string | null }
/**
 * The supervisor's self-assessment of the proposed plan against
 * each of the four authority bounds. Carried on `PlanProposed`
 * when the supervisor adapter emits it. Decompositions without an envelope
 * pause only when `MissionSpec.confirm_plan == Some(true)`.
 */
export type EnvelopeFit = { scope: BoundFit; reversibility: BoundFit; risk: BoundFit; quality: BoundFit }
/**
 * Carries enough detail for the inbox card (S3) to explain what
 * tripped to the user, without re-parsing the audit report.
 */
export type EscalationEvidence = { 
/**
 * Free-form human-readable explanation. Keep < 200 chars; long
 * detail goes in `payload_json`.
 */
summary: string; 
/**
 * Optional machine-readable JSON blob. Used by the inbox to
 * render structured breakdowns (e.g. list of out-of-scope
 * paths, list of failing tests).
 */
payload_json: string | null }
/**
 * Canonical event envelope. The `kind` field is flattened into the
 * outer object so the wire format is exactly the envelope shown in
 * the crate-level docs.
 */
export type Event = ({ type: "state_change"; payload: StateChange } | { type: "log"; payload: Log } | { type: "progress"; payload: Progress } | { type: "file_activity"; payload: FileActivity } | { type: "test_result"; payload: TestResult } | { type: "cost"; payload: Cost } | { type: "dependency"; payload: Dependency } | { type: "completion"; payload: Completion } | { type: "failure"; payload: Failure }) & { schema_version: string; worker_id: string; task_id: string | null; seq: number; ts: string }
/**
 * Discriminated payload union. Adjacently tagged: `{"type": "...",
 * "payload": {...}}`. `rename_all = "snake_case"` defines the
 * canonical wire names.
 */
export type EventKind = { type: "state_change"; payload: StateChange } | { type: "log"; payload: Log } | { type: "progress"; payload: Progress } | { type: "file_activity"; payload: FileActivity } | { type: "test_result"; payload: TestResult } | { type: "cost"; payload: Cost } | { type: "dependency"; payload: Dependency } | { type: "completion"; payload: Completion } | { type: "failure"; payload: Failure }
/**
 * Verdict for a single mission event. The frontend ingest layer
 * consults this verdict via a Tauri command (Task 11) and routes
 * the event accordingly.
 * 
 * `Internal` events ARE persisted to the event log (for debugging
 * and replay) but never surfaced to the UI in any mode.
 * `PowerUserOnly` events build the legacy attention/comms feed
 * state only when the user enables "Show all events".
 * `Inbox` events always produce an inbox card with the carried
 * `kind` + `severity`.
 */
export type EventVisibility = { kind: "internal" } | { kind: "power_user_only" } | { kind: "inbox"; inbox_kind: InboxKind; severity: Severity }
export type Failure = { error: string; retryable: boolean; suggestion?: string | null; exit_code?: number | null; category?: FailureCategory | null }
export type FailureCategory = "timeout" | "auth" | "network" | "rate_limit" | "tool_error" | "task_logic" | "internal" | "unknown"
export type FileActivity = { path: string; op: FileOp; from_path?: string | null; lines_added?: number | null; lines_removed?: number | null; bytes?: number | null }
export type FileOp = "created" | "modified" | "deleted" | "renamed" | "read"
export type HealthDto = { version: string; uptime_ms: number }
/**
 * What kind of inbox card the event produces.
 * 
 * - `Escalation` — the arbiter escalated; user input is required
 * before the mission can proceed.
 * - `Completion` — the mission reached a terminal Accept or
 * Scrub. The card stays in the inbox as the user's record of
 * what shipped.
 * - `SideEffect` — a declared side effect (package install, API
 * call, etc.) requires user awareness even though no decision
 * is needed. Always `Severity::Warning`.
 */
export type InboxKind = "escalation" | "completion" | "side_effect"
export type LintScore = { rustfmt_clean: boolean | null; clippy_warnings: number | null; biome_diagnostics: number | null; score: number }
export type Log = { level: LogLevel; stream: LogStream; line: string; tag?: string | null }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type LogStream = "stdout" | "stderr"
export type MemoryBundleDto = { bundle_id: string; mission_id: string; worker_id: string; turn: number; vendor: string; note_ids: string[] }
export type MemoryEventDto = { event_id: string; mission_id: string | null; worker_id: string | null; ts: string; kind: MemoryEventKindDto }
/**
 * UI-friendly memory event projection. Each variant carries only
 * the fields the drawer needs; the raw payload stays in
 * `memory_events.payload_json` for anyone who needs more.
 */
export type MemoryEventKindDto = { type: "proposed"; proposal_id: string; kind: string; body_preview: string } | { type: "proposal_rejected"; proposal_id: string; reason: string } | { type: "normalized"; proposal_id: string } | { type: "ratified"; proposal_id: string; note_id: string | null; decision: string } | { type: "rejected"; proposal_id: string; reason: string } | { type: "promoted"; note_id: string; confidence: number } | { type: "barrier"; kind: string } | { type: "bundle_composed"; bundle_id: string; worker_id: string; turn: number; note_count: number } | { type: "bundle_rendered"; bundle_id: string } | { type: "drift_detected"; bundle_id: string } | 
/**
 * Catch-all for events the UI doesn't render specifically.
 * Carries the wire type name so a future UI build can opt in
 * without a new server round-trip.
 */
{ type: "other"; event_type: string }
/**
 * Lightweight summary returned by [`memory_list_notes`]. Bodies are
 * omitted on purpose — the list endpoint should stay cheap; the
 * drawer in Tier-2E will introduce a separate "show note" command
 * when the body is actually needed.
 */
export type MemoryNoteSummaryDto = { id: string; kind: string; scope_kind: string; scope_value: string | null; state: string; created_at: string }
/**
 * How the user disposed of a completed mission.
 */
export type MergeResolution = { type: "merged" } | { type: "discarded" } | 
/**
 * Retained for decoding historical/replayed events. Current runtimes do
 * not emit this resolution until a real supervisor re-entry path exists.
 */
{ type: "extended"; directive: string | null }
/**
 * Envelope shared by every mission event. `seq` is monotonic per
 * mission; `ts` is RFC 3339 UTC with millisecond precision.
 */
export type MissionEvent = ({ type: "mission.created"; payload: { spec: MissionSpec } } | { type: "mission.execution_started" } | { type: "supervisor.decomposition"; payload: { tasks: TaskDescriptor[] } } | 
/**
 * The supervisor produced a decomposition that does not form a DAG
 * (cycle / orphan dependency / duplicate index / empty).
 * `reason` is the serialized [`crate::task_graph::GraphError`]
 * for forward-compat — the orchestrator deserializes for the
 * inbox card; the frontend treats it opaquely.
 */
{ type: "supervisor.decomposition_rejected"; payload: { reason: string } } | 
/**
 * Emitted after each (re)decomposition when plan confirmation is required.
 * when `MissionSpec.confirm_plan == Some(true)`. `generation` is
 * monotonically increasing within a mission; 0 is the first
 * proposed plan, incremented on each regeneration.
 * 
 * The optional rich-context fields default so older event rows and
 * adapters retain the same confirmation behavior.
 */
{ type: "plan.proposed"; payload: { tasks: TaskDescriptor[]; generation: number; 
/**
 * Short prose summary of the proposed plan. Rendered
 * above the task list in `MissionPlanPreview`. `None` for
 * supervisor adapters that haven't been updated to emit it.
 */
overview?: string | null; 
/**
 * Typed tech-stack rows. Rendered as a small badge
 * list; `is_new` rows get a `[new]` glyph.
 */
tech_stack?: TechChoice[] | null; 
/**
 * Supervisor's four-bound self-assessment of the
 * plan. When any bound is `Exceeds`, the orchestrator
 * forces `PendingPlanApproval` even if
 * `MissionSpec.confirm_plan != Some(true)`. `None` means
 * the supervisor did not classify (legacy or
 * envelope-unaware adapter).
 */
envelope_fit?: EnvelopeFit | null } } | 
/**
 * The user accepted the proposed plan; workers are about to
 * spawn. The `generation` matches the accepted `PlanProposed`.
 */
{ type: "plan.confirmed"; payload: { generation: number } } | 
/**
 * The user asked for a new decomposition. `hint` is the
 * optional natural-language feedback the user supplied;
 * `prior_generation` identifies which proposed plan they
 * rejected.
 */
{ type: "plan.regeneration_requested"; payload: { hint: string | null; prior_generation: number } } | 
/**
 * The user rejected the proposed plan from
 * `MissionPlanPreview`. The mission transitions to `Aborted`
 * directly after this event; the `reason` is the optional
 * free-form text from the FE reject form. `generation` matches
 * the rejected `PlanProposed`.
 */
{ type: "plan.rejected"; payload: { generation: number; reason?: string | null } } | { type: "worker.spawned"; payload: { worker_id: string; task_index: number; task_title: string } } | { type: "worker.progress"; payload: { worker_id: string; note: string } } | { type: "worker.result_submitted"; payload: { worker_id: string; files: string[]; summary: string } } | { type: "supervisor.review_started"; payload: { worker_id: string } } | { type: "supervisor.integrated"; payload: { worker_id: string; integration_sha: string; snapshot_tag: string } } | { type: "supervisor.test_result"; payload: { passed: boolean; summary: string } } | { type: "supervisor.audit_completed"; payload: { 
/**
 * Tier as a string ("smoke" | "standard" | "deep") so the
 * schema doesn't depend on the audit module's AuditTier enum
 * (which lives in a different crate root).
 */
tier: string; overall: number; 
/**
 * Full serialized AuditReport. Opaque to the event-schema
 * boundary; consumers parse on demand.
 */
payload_json: string } } | 
/**
 * The arbiter has rendered a decision over a
 * worker's submission. Carries the decision as JSON (typed enums
 * would force a churning event-schema dependency) plus the audit
 * composite for the inbox card. `bound` is set only for the
 * Escalate variant; `None` for Accept/Extend/Scrub.
 */
{ type: "arbiter.decided"; payload: { worker_id: string; decision_json: string; audit_overall: number; bound: AuthorityBound | null } } | 
/**
 * Every in-flight task has quiesced after a scrub or escalation, so the
 * user may now safely choose Merge or Discard for the partial mission.
 */
{ type: "mission.attention_ready" } | 
/**
 * A mission previously merged into its target branch has been undone by
 * the `revert_mission` Tauri command. `restored_sha` is the new revert
 * commit. The `pre_merge_tag` field name is retained for wire
 * compatibility; for final merges it carries the persistent `before`
 * rollback anchor.
 */
{ type: "mission.reverted"; payload: { restored_sha: string; pre_merge_tag: string } } | 
/**
 * Audit re-run after worker integration on the supervisor
 * branch. Detects regressions introduced by the rebase/merge
 * itself (e.g., a test that passed in the worker's worktree but
 * fails post-merge because of an unrelated change in
 * supervisor/main since the rebase base). When `overall` falls
 * below `policy.quality_min`, the mission enters Attention with a
 * Reversibility escalation and preserves the workspace for review.
 */
{ type: "supervisor.post_integration_audit_completed"; payload: { worker_id: string; tier: string; overall: number; payload_json: string } } | { type: "mission.completed"; payload: { summary: string; files_changed: number } } | { type: "mission.merge_resolved"; payload: { resolution: MergeResolution } } | { type: "mission.aborted"; payload: { reason: string } } | 
/**
 * A worker surfaced an operation that can
 * affect the machine or outside world beyond the repo diff. This
 * is intentionally visible and auditable rather than magically
 * reversible: Discard cleans Vigla branches/worktrees, but
 * package installs, paid API calls, network egress, and external
 * mutations remain real side effects.
 */
{ type: "boundary.side_effect_logged"; payload: { worker_id: string; kind: DeclaredSideEffectKind; summary: string; declared: boolean } } | 
/**
 * Permanent single-supervisor boundary. Emitted when the supervisor's intent
 * stream requests spawning a worker whose role would itself be
 * "supervisor" — the orchestrator refuses the spawn and surfaces
 * the refusal on the mission-event channel so it lands in
 * Attention. The team metaphor stops at one level of supervision.
 */
{ type: "boundary.sub_supervisor_refused"; payload: { requested_by_supervisor_id: string; requested_worker_id: string } } | 
/**
 * Retained for forward-compatible replay of the earlier extension event
 * shape. Current runtimes reject Extend rather than emit an event without
 * scheduling a real supervisor turn.
 */
{ type: "mission.extended"; payload: { directive: string | null } } | 
/**
 * The recovery engine decided on a failure path. Carries the
 * classified FailureClass and the chosen RecoveryAction both
 * as JSON strings — the recovery types live in the orchestrator
 * crate and the event schema is forward-compat-only, so we
 * keep typed enums out of the wire format. The escalation layer owns
 * visibility routing.
 */
{ type: "supervisor.recovery_decided"; payload: { worker_id: string; class_json: string; action_json: string } } | 
/**
 * The mission entered `MissionState::Paused`. `reason_json`
 * carries the typed PauseReason; `estimated_resume_at_ms` is
 * the Unix-ms timestamp the wake-up task will trigger on.
 */
{ type: "mission.paused"; payload: { reason_json: string; estimated_resume_at_ms: number } } | 
/**
 * The mission transitioned from Paused back to Executing.
 * `vendor` identifies which vendor's quota window reopened.
 */
{ type: "mission.resumed"; payload: { vendor: Vendor } } | 
/**
 * Memory attach exceeded the rendered bundle's token budget.
 * bundle because the worker's token budget was below the
 * composer's natural output. Telemetry only — not surfaced
 * to the user.
 */
{ type: "supervisor.context_budget_exceeded"; payload: { worker_id: string; requested_tokens: number; granted_tokens: number; dropped_entries: number } } | 
/**
 * A worker left a structured note for a downstream task. Routed by the
 * DAG scheduler and
 * optionally persisted by the memory kernel. `to_role` is
 * the worker role the upstream worker intends as the
 * audience.
 */
{ type: "supervisor.handoff_note"; payload: { from_worker: string; to_role: WorkerRole; note: string } } | 
/**
 * A worker emitted a `RequestContext`
 * signal and the supervisor's memory matcher could not
 * satisfy it. Telemetry only — the follow-up
 * `ArbiterDecided { bound: Some(Scope), … }` event carries
 * the inbox card.
 */
{ type: "supervisor.context_request_unmet"; payload: { worker_id: string; 
/**
 * Stringified [`crate::recovery::ContextRequestKind`]
 * (e.g. "file_content", "documentation", "prior_decision").
 */
kind: string; detail: string } } | 
/**
 * The mission runtime assembled the mission-level completion verdict.
 * Carries the serialized
 * [`crate::judgment::CompletionVerdict`] as JSON. Visibility
 * routes this through [`crate::escalation::visibility_for`]:
 * happy verdicts (`recommendation = Accept`) land as
 * `Inbox{Completion, Info}`; fail-closed `Scrub` recommendations
 * land as `Inbox{Escalation, Warning}`.
 */
{ type: "mission.completion_verdict_rendered"; payload: { payload_json: string } } | 
/**
 * The memory composer truncated a
 * worker's bundle to fit the token budget. This event
 * fires AFTER successful re-render — it signals truncation
 * success. The pre-existing
 * [`Self::ContextBudgetExceeded`] event still fires first
 * (telemetry "we noticed the overflow"); this event signals
 * "we recovered." Both events live for replay and
 * debugging. Unresolved-issues collector consumes this
 * variant.
 */
{ type: "supervisor.context_budget_truncated"; payload: { worker_id: string; original_bytes: number; rendered_bytes: number; dropped_note_ids: string[] } } | 
/**
 * A memory bundle was composed
 * for a worker. Fires from both compose paths:
 * * `Manual` — explicit pin set passed in (the legacy
 * [`crate::memory::attach_to_worktree`] path); `mmr_lambda`
 * is always `None`.
 * * `Retrieval` — driven by [`crate::memory::composer::RetrievalBrief`]
 * through [`crate::memory::MemoryKernel::compose_retrieval`].
 * `mmr_lambda` is `Some(λ)` **iff MMR re-rank actually ran**
 * (i.e. at least one candidate had a stored embedding —
 * hybrid relevance + MMR diversity); `None` if the path
 * fell back to BM25-only (no stored vectors yet during the
 * embedding-backfill warm-up window, or the `embeddings`
 * cargo feature is off). Replay can therefore tell hybrid
 * retrieval, BM25-only fallback, and manual composer
 * apart from this field alone.
 * 
 * Telemetry only — never user-visible. `candidate_count` is
 * the number of notes the composer was handed by its picker
 * **before any composer-side budget truncation** — post-MMR
 * for the retrieval path; equal to the supplied id-list
 * length for the manual path. (NB: not the same as the final
 * rendered page-table length, which may be shorter once the
 * worker's token budget is enforced.)
 */
{ type: "memory.context_bundle_composed"; payload: { bundle_id: string; source: ComposeSource; candidate_count: number; mmr_lambda: number | null } } | 
/**
 * Telemetry: curated skill playbooks attached to a worker before dispatch.
 * Telemetry-only (no escalation/inbox routing), like `ContextBundleComposed`.
 */
{ type: "skills.attached"; payload: { worker_id: string; skill_ids: string[]; tokens: number; dropped: string[] } }) & { mission_id: string; seq: number; ts: string }
/**
 * Emitted to the frontend on each mission-level event. Transparent
 * newtype so the wire payload is exactly the
 * `orchestrator::MissionEvent` shape (mission_id, seq, ts, kind).
 */
export type MissionEventDto = MissionEvent
/**
 * Discriminated payload union. Variant names use the dotted wire
 * form from proposal v2 §3.6 (e.g. `"mission.created"`).
 */
export type MissionEventKind = { type: "mission.created"; payload: { spec: MissionSpec } } | { type: "mission.execution_started" } | { type: "supervisor.decomposition"; payload: { tasks: TaskDescriptor[] } } | 
/**
 * The supervisor produced a decomposition that does not form a DAG
 * (cycle / orphan dependency / duplicate index / empty).
 * `reason` is the serialized [`crate::task_graph::GraphError`]
 * for forward-compat — the orchestrator deserializes for the
 * inbox card; the frontend treats it opaquely.
 */
{ type: "supervisor.decomposition_rejected"; payload: { reason: string } } | 
/**
 * Emitted after each (re)decomposition when plan confirmation is required.
 * when `MissionSpec.confirm_plan == Some(true)`. `generation` is
 * monotonically increasing within a mission; 0 is the first
 * proposed plan, incremented on each regeneration.
 * 
 * The optional rich-context fields default so older event rows and
 * adapters retain the same confirmation behavior.
 */
{ type: "plan.proposed"; payload: { tasks: TaskDescriptor[]; generation: number; 
/**
 * Short prose summary of the proposed plan. Rendered
 * above the task list in `MissionPlanPreview`. `None` for
 * supervisor adapters that haven't been updated to emit it.
 */
overview?: string | null; 
/**
 * Typed tech-stack rows. Rendered as a small badge
 * list; `is_new` rows get a `[new]` glyph.
 */
tech_stack?: TechChoice[] | null; 
/**
 * Supervisor's four-bound self-assessment of the
 * plan. When any bound is `Exceeds`, the orchestrator
 * forces `PendingPlanApproval` even if
 * `MissionSpec.confirm_plan != Some(true)`. `None` means
 * the supervisor did not classify (legacy or
 * envelope-unaware adapter).
 */
envelope_fit?: EnvelopeFit | null } } | 
/**
 * The user accepted the proposed plan; workers are about to
 * spawn. The `generation` matches the accepted `PlanProposed`.
 */
{ type: "plan.confirmed"; payload: { generation: number } } | 
/**
 * The user asked for a new decomposition. `hint` is the
 * optional natural-language feedback the user supplied;
 * `prior_generation` identifies which proposed plan they
 * rejected.
 */
{ type: "plan.regeneration_requested"; payload: { hint: string | null; prior_generation: number } } | 
/**
 * The user rejected the proposed plan from
 * `MissionPlanPreview`. The mission transitions to `Aborted`
 * directly after this event; the `reason` is the optional
 * free-form text from the FE reject form. `generation` matches
 * the rejected `PlanProposed`.
 */
{ type: "plan.rejected"; payload: { generation: number; reason?: string | null } } | { type: "worker.spawned"; payload: { worker_id: string; task_index: number; task_title: string } } | { type: "worker.progress"; payload: { worker_id: string; note: string } } | { type: "worker.result_submitted"; payload: { worker_id: string; files: string[]; summary: string } } | { type: "supervisor.review_started"; payload: { worker_id: string } } | { type: "supervisor.integrated"; payload: { worker_id: string; integration_sha: string; snapshot_tag: string } } | { type: "supervisor.test_result"; payload: { passed: boolean; summary: string } } | { type: "supervisor.audit_completed"; payload: { 
/**
 * Tier as a string ("smoke" | "standard" | "deep") so the
 * schema doesn't depend on the audit module's AuditTier enum
 * (which lives in a different crate root).
 */
tier: string; overall: number; 
/**
 * Full serialized AuditReport. Opaque to the event-schema
 * boundary; consumers parse on demand.
 */
payload_json: string } } | 
/**
 * The arbiter has rendered a decision over a
 * worker's submission. Carries the decision as JSON (typed enums
 * would force a churning event-schema dependency) plus the audit
 * composite for the inbox card. `bound` is set only for the
 * Escalate variant; `None` for Accept/Extend/Scrub.
 */
{ type: "arbiter.decided"; payload: { worker_id: string; decision_json: string; audit_overall: number; bound: AuthorityBound | null } } | 
/**
 * Every in-flight task has quiesced after a scrub or escalation, so the
 * user may now safely choose Merge or Discard for the partial mission.
 */
{ type: "mission.attention_ready" } | 
/**
 * A mission previously merged into its target branch has been undone by
 * the `revert_mission` Tauri command. `restored_sha` is the new revert
 * commit. The `pre_merge_tag` field name is retained for wire
 * compatibility; for final merges it carries the persistent `before`
 * rollback anchor.
 */
{ type: "mission.reverted"; payload: { restored_sha: string; pre_merge_tag: string } } | 
/**
 * Audit re-run after worker integration on the supervisor
 * branch. Detects regressions introduced by the rebase/merge
 * itself (e.g., a test that passed in the worker's worktree but
 * fails post-merge because of an unrelated change in
 * supervisor/main since the rebase base). When `overall` falls
 * below `policy.quality_min`, the mission enters Attention with a
 * Reversibility escalation and preserves the workspace for review.
 */
{ type: "supervisor.post_integration_audit_completed"; payload: { worker_id: string; tier: string; overall: number; payload_json: string } } | { type: "mission.completed"; payload: { summary: string; files_changed: number } } | { type: "mission.merge_resolved"; payload: { resolution: MergeResolution } } | { type: "mission.aborted"; payload: { reason: string } } | 
/**
 * A worker surfaced an operation that can
 * affect the machine or outside world beyond the repo diff. This
 * is intentionally visible and auditable rather than magically
 * reversible: Discard cleans Vigla branches/worktrees, but
 * package installs, paid API calls, network egress, and external
 * mutations remain real side effects.
 */
{ type: "boundary.side_effect_logged"; payload: { worker_id: string; kind: DeclaredSideEffectKind; summary: string; declared: boolean } } | 
/**
 * Permanent single-supervisor boundary. Emitted when the supervisor's intent
 * stream requests spawning a worker whose role would itself be
 * "supervisor" — the orchestrator refuses the spawn and surfaces
 * the refusal on the mission-event channel so it lands in
 * Attention. The team metaphor stops at one level of supervision.
 */
{ type: "boundary.sub_supervisor_refused"; payload: { requested_by_supervisor_id: string; requested_worker_id: string } } | 
/**
 * Retained for forward-compatible replay of the earlier extension event
 * shape. Current runtimes reject Extend rather than emit an event without
 * scheduling a real supervisor turn.
 */
{ type: "mission.extended"; payload: { directive: string | null } } | 
/**
 * The recovery engine decided on a failure path. Carries the
 * classified FailureClass and the chosen RecoveryAction both
 * as JSON strings — the recovery types live in the orchestrator
 * crate and the event schema is forward-compat-only, so we
 * keep typed enums out of the wire format. The escalation layer owns
 * visibility routing.
 */
{ type: "supervisor.recovery_decided"; payload: { worker_id: string; class_json: string; action_json: string } } | 
/**
 * The mission entered `MissionState::Paused`. `reason_json`
 * carries the typed PauseReason; `estimated_resume_at_ms` is
 * the Unix-ms timestamp the wake-up task will trigger on.
 */
{ type: "mission.paused"; payload: { reason_json: string; estimated_resume_at_ms: number } } | 
/**
 * The mission transitioned from Paused back to Executing.
 * `vendor` identifies which vendor's quota window reopened.
 */
{ type: "mission.resumed"; payload: { vendor: Vendor } } | 
/**
 * Memory attach exceeded the rendered bundle's token budget.
 * bundle because the worker's token budget was below the
 * composer's natural output. Telemetry only — not surfaced
 * to the user.
 */
{ type: "supervisor.context_budget_exceeded"; payload: { worker_id: string; requested_tokens: number; granted_tokens: number; dropped_entries: number } } | 
/**
 * A worker left a structured note for a downstream task. Routed by the
 * DAG scheduler and
 * optionally persisted by the memory kernel. `to_role` is
 * the worker role the upstream worker intends as the
 * audience.
 */
{ type: "supervisor.handoff_note"; payload: { from_worker: string; to_role: WorkerRole; note: string } } | 
/**
 * A worker emitted a `RequestContext`
 * signal and the supervisor's memory matcher could not
 * satisfy it. Telemetry only — the follow-up
 * `ArbiterDecided { bound: Some(Scope), … }` event carries
 * the inbox card.
 */
{ type: "supervisor.context_request_unmet"; payload: { worker_id: string; 
/**
 * Stringified [`crate::recovery::ContextRequestKind`]
 * (e.g. "file_content", "documentation", "prior_decision").
 */
kind: string; detail: string } } | 
/**
 * The mission runtime assembled the mission-level completion verdict.
 * Carries the serialized
 * [`crate::judgment::CompletionVerdict`] as JSON. Visibility
 * routes this through [`crate::escalation::visibility_for`]:
 * happy verdicts (`recommendation = Accept`) land as
 * `Inbox{Completion, Info}`; fail-closed `Scrub` recommendations
 * land as `Inbox{Escalation, Warning}`.
 */
{ type: "mission.completion_verdict_rendered"; payload: { payload_json: string } } | 
/**
 * The memory composer truncated a
 * worker's bundle to fit the token budget. This event
 * fires AFTER successful re-render — it signals truncation
 * success. The pre-existing
 * [`Self::ContextBudgetExceeded`] event still fires first
 * (telemetry "we noticed the overflow"); this event signals
 * "we recovered." Both events live for replay and
 * debugging. Unresolved-issues collector consumes this
 * variant.
 */
{ type: "supervisor.context_budget_truncated"; payload: { worker_id: string; original_bytes: number; rendered_bytes: number; dropped_note_ids: string[] } } | 
/**
 * A memory bundle was composed
 * for a worker. Fires from both compose paths:
 * * `Manual` — explicit pin set passed in (the legacy
 * [`crate::memory::attach_to_worktree`] path); `mmr_lambda`
 * is always `None`.
 * * `Retrieval` — driven by [`crate::memory::composer::RetrievalBrief`]
 * through [`crate::memory::MemoryKernel::compose_retrieval`].
 * `mmr_lambda` is `Some(λ)` **iff MMR re-rank actually ran**
 * (i.e. at least one candidate had a stored embedding —
 * hybrid relevance + MMR diversity); `None` if the path
 * fell back to BM25-only (no stored vectors yet during the
 * embedding-backfill warm-up window, or the `embeddings`
 * cargo feature is off). Replay can therefore tell hybrid
 * retrieval, BM25-only fallback, and manual composer
 * apart from this field alone.
 * 
 * Telemetry only — never user-visible. `candidate_count` is
 * the number of notes the composer was handed by its picker
 * **before any composer-side budget truncation** — post-MMR
 * for the retrieval path; equal to the supplied id-list
 * length for the manual path. (NB: not the same as the final
 * rendered page-table length, which may be shorter once the
 * worker's token budget is enforced.)
 */
{ type: "memory.context_bundle_composed"; payload: { bundle_id: string; source: ComposeSource; candidate_count: number; mmr_lambda: number | null } } | 
/**
 * Telemetry: curated skill playbooks attached to a worker before dispatch.
 * Telemetry-only (no escalation/inbox routing), like `ContextBundleComposed`.
 */
{ type: "skills.attached"; payload: { worker_id: string; skill_ids: string[]; tokens: number; dropped: string[] } }
/**
 * Thin DTO wrapper — `MissionEventKind` is `#[serde(tag = "type",
 * content = "payload")]`, so this struct passes through unchanged.
 * Specta picks up the inner enum's bindings.
 */
export type MissionEventKindDto = MissionEventKind
/**
 * One row in the MissionHistory view. Outcome state is authoritative for
 * whether the frontend may offer a rollback.
 */
export type MissionHistoryRow = { mission_id: string; tier: string; audit_overall: number; created_at: string; reverted: boolean; status: MissionHistoryStatusDto; target_ref: string | null; repo_root: string | null; artifacts_cleaned: boolean }
export type MissionHistoryStatusDto = "audited" | "merged" | "discarded" | "aborted"
/**
 * User-provided mission input. `title` and `objective` are required;
 * `target_ref` defaults to the repo's current HEAD at the call site;
 * `tests` is optional. `supervisor_model` picks which vendor CLI
 * runs as the supervisor (default in the UI is Claude).
 * `worker_model` and `worker_count` are `None` by default —
 * meaning worker vendors are routed by task role and the supervisor
 * decides how many tasks to spawn based on the objective. A single
 * `worker_model` value pins all workers to one vendor; a comma-
 * separated value (for example `claude,codex,gemini`) pins each
 * selected worker independently by task index.
 */
export type MissionSpec = { title: string; objective: string; target_ref: string; tests: string | null; supervisor_model: string | null; worker_model: string | null; worker_count: number | null; 
/**
 * QC-2: when `Some(true)`, the orchestrator pauses after the
 * supervisor's decomposition turn (state moves to
 * `MissionState::PendingPlanApproval`) and waits for the user
 * to either confirm or request a regeneration via the
 * `confirm_plan` / `regenerate_plan` IPC commands. Default
 * `None` preserves the autonomous "two touches" flow.
 */
confirm_plan: boolean | null; 
/**
 * Allowed-files allow-list for audit scope-adherence scoring.
 * Empty means "no constraint" (everything is in-scope). Paths
 * are relative to the worktree root.
 */
scope_paths?: string[] }
export type NoteStateFilter = "owned" | "promoted" | "disputed" | "invalid"
/**
 * User-controlled subset of note kinds. The kernel's
 * `NoteKind::Other(String)` variant is intentionally hidden from the
 * IPC surface — pinning a freshly-coined kind would require a
 * taxonomy migration first, and that's an admin-class operation, not
 * a "pin a note" one. Constraining the wire form to the four
 * standard kinds keeps the UI dropdown finite and the kernel happy.
 */
export type PinNoteKind = "fact" | "decision" | "procedure" | "hazard"
export type PinNoteRejectReason = "secret" | "oversize" | "malformed"
export type PinNoteRequest = { kind: PinNoteKind; scope_kind: PinNoteScopeKind; 
/**
 * Required for any scope other than `repo`. Validated by the
 * kernel; the IPC surface only forwards it.
 */
scope_value?: string | null; body: string }
export type PinNoteResponse = 
/**
 * Note created. `promoted == true` when the policy shortcut for
 * `UserAuthored` witnesses cleared the bar (single-pin learning
 * loop succeeded).
 */
{ outcome: "pinned"; note_id: string; promoted: boolean } | 
/**
 * Scanner / oversize check rejected the body. No note created;
 * only the redacted preview survives in the event log.
 */
{ outcome: "rejected"; reason: PinNoteRejectReason; redacted_preview: string }
/**
 * User-controlled scope. `repo` is the default; `vendor` requires a
 * vendor name. `path`/`supervisor`/`worker` scopes need a value
 * supplied by the frontend.
 */
export type PinNoteScopeKind = "repo" | "vendor" | "path"
export type Progress = { percent: number; eta_ms?: number | null; note?: string | null }
export type RegressionScore = { baseline_passed: boolean; current_passed: boolean; newly_failing: string[]; newly_passing: string[]; score: number }
/**
 * User disposition at mission complete. Only valid from
 * [`MissionState::CompletePendingMerge`]; see [`Self::allowed_from`].
 */
export type ResolveAction = { type: "merge" } | { type: "discard" } | 
/**
 * Reserved wire variant retained so older persisted events and clients
 * remain decodable. The runtime fails closed with
 * `ExtensionUnsupported` until supervisor re-entry is implemented.
 */
{ type: "extend"; directive: string | null }
/**
 * DTO for the `revert_mission` command. Mirrors
 * `orchestrator::mission_workspace::RevertOutcome` but lives in the
 * host crate so specta can derive the TS binding without making
 * the orchestrator depend on `specta`.
 */
export type RevertOutcomeDto = { restored_sha: string; pre_merge_tag: string }
export type ReworkKind = 
/**
 * Re-run the same worker with a directive. Cheapest. Arbiter's
 * default when the supervisor hasn't picked something specific.
 */
{ kind: "revise"; directive: string } | 
/**
 * Tear down the failing worker, spawn a fresh one. Optional
 * vendor swap. Use when the worker is stuck in a loop / lost
 * context, or the vendor is a poor match for the task. `from_worker`
 * is the worker_id being torn down; fresh id is generated by
 * mission loop (`{base}-r{attempt}`). `to_vendor: None` keeps
 * current vendor.
 */
{ kind: "reassign"; from_worker: string; to_vendor: Vendor | null } | 
/**
 * Replace the current task with N smaller sub-tasks. Descriptor indices
 * are local to the replacement; the mission loop remaps them into the
 * live DAG after the current task.
 */
{ kind: "split"; sub_tasks: TaskDescriptor[] } | 
/**
 * Re-run with a constrained scope_paths overlay. Applies to the
 * next pass only. Empty means "no constraint" (Revise-equivalent).
 * The dispatcher enforces this through the file ACL before integration.
 */
{ kind: "narrow"; reduced_scope: string[] } | 
/**
 * Re-run with a fully replaced brief. Used in place of
 * `task.title` for the next pass.
 */
{ kind: "rebrief"; new_brief: string } | 
/**
 * Supervisor declares the task cannot be automated to passing. The
 * reviewable workspace is retained and the mission advances to Attention.
 */
{ kind: "mark_unachievable"; rationale: string }
/**
 * Closed 3-band residual-risk classification.
 * 
 * Heuristic boundaries (see
 * [`crate::judgment::risk_band::score_risk`]):
 * 
 * * `Low` when `audit.overall >= 0.85` AND zero security flags.
 * * `Medium` when `0.7 <= overall < 0.85` OR a single security
 * flag with no audit floor breach.
 * * `High` otherwise (overall below floor or multiple flags).
 */
export type RiskBand = "low" | "medium" | "high"
export type ScopeScore = { in_scope: number; out_of_scope: number; score: number }
export type ScrubReason = 
/**
 * Quality floor unreachable inside the rework budget.
 */
{ kind: "quality_exhausted" } | 
/**
 * Audit ran but produced no usable score (infrastructure
 * failure — test runner missing, lint runner panicked, etc.).
 */
{ kind: "audit_unusable" }
export type SecurityFlag = { kind: SecurityFlagKind; path: string; detail: string }
export type SecurityFlagKind = "SecretFile" | "SchemaMigration" | "MassDeletion"
/**
 * Severity of an inbox card. Drives visual treatment + the
 * "should we fire the macOS native banner" decision (only
 * `ActionRequired` triggers the banner).
 */
export type Severity = 
/**
 * Informational. Renders as a soft card; no notification.
 */
"info" | 
/**
 * Something to be aware of. Renders with a warning glyph; no
 * native banner.
 */
"warning" | 
/**
 * User input required. Always fires the macOS native banner
 * when the app is not focused.
 */
"action_required"
export type StartupPhaseDto = "initializing" | "ready" | "failed"
export type StartupStatusDto = { phase: StartupPhaseDto; error: string | null }
export type StateChange = { state: WorkerState; from?: WorkerState | null; note?: string | null }
export type StoredPlaybook = { id: string; json: string }
export type SuggestedUserAction = 
/**
 * User to narrow scope or co-sign the out-of-scope diff.
 */
{ kind: "confirm_scope"; out_of_scope_paths: string[] } | 
/**
 * User to co-sign a risky operation (schema migration, mass
 * delete, secret-touching change, etc.).
 */
{ kind: "co_sign_risk"; detail: string } | 
/**
 * User to acknowledge the irrecoverable state and choose
 * merge-partial / discard.
 */
{ kind: "resolve_mission" } | 
/**
 * QC-3: open `MissionPlanPreview` and approve / regenerate /
 * reject. Emitted by `plan_envelope_check::check` when the
 * supervisor's `envelope_fit` trips a bound at decompose time
 * — before any worker has run. Distinct from `ConfirmScope` /
 * `CoSignRisk` which arrive post-audit.
 */
{ kind: "review_plan" }
/**
 * One unit of work in the supervisor's decomposition.
 * 
 * Dependency edges, role, acceptance criteria, scope, and description all
 * default for compatibility with earlier `{ index, title }` event rows.
 */
export type TaskDescriptor = { index: number; title: string; 
/**
 * Index references to other tasks in the same decomposition
 * that must complete before this one starts. Must form a DAG
 * (no cycles, no orphan refs); validated by
 * [`crate::task_graph::validate`] at decomposition emit time.
 */
depends_on?: number[]; 
/**
 * What kind of work this is. Influences vendor routing via
 * [`crate::task_graph::select_vendor_for_role`].
 */
role?: TaskRole; 
/**
 * Pass/fail conditions evaluated post-audit. Empty criteria
 * reduce to "any arbiter Accept is sufficient".
 */
criteria?: AcceptanceCriteria; 
/**
 * Per-task allow-list. Intersected with
 * `MissionSpec.scope_paths` (per-task wins inside the
 * intersection). Empty inherits the mission-level scope.
 * Enforced before audit and integration by the per-worker ACL gate.
 */
scope_paths?: string[]; 
/**
 * Free-form supervisor-authored elaboration of `title`. Memory retrieval
 * includes its keywords in the worker's `RetrievalBrief` query.
 */
description?: string | null }
/**
 * Task identity record. `depends_on` drives dependency-aware dispatch.
 */
export type TaskInfo = { id: string; parent_id: string | null; title: string; depends_on: string[]; created_at: string }
/**
 * What kind of work this task represents. The arbiter uses this to
 * pick a default vendor in [`super::role_routing::select_vendor_for_role`].
 * 
 * Distinct from [`crate::mission_runtime::WorkerRole`] (which is the
 * Supervisor/Employee boundary check). Do not reuse that name.
 */
export type TaskRole = 
/**
 * Default — produces production code or docs.
 */
"implementer" | 
/**
 * Writes / extends tests, runs the suite, surfaces regressions.
 */
"tester" | 
/**
 * Reads the integrated branch, surfaces critique or polish.
 */
"reviewer"
/**
 * One row of the supervisor's `tech_stack` summary. `layer` is a
 * short descriptor (e.g. `"framework"`, `"database"`,
 * `"test runner"`), `choice` is the specific selection
 * (e.g. `"Tauri 2"`, `"SQLite"`), and `is_new` flags stack
 * elements not already present in the user's repo so the FE can
 * badge them.
 */
export type TechChoice = { layer: string; choice: string; rationale: string; is_new?: boolean }
export type TestFailure = { name: string; message: string; file?: string | null; line?: number | null }
export type TestPassScore = { ran: boolean; passed: number; failed: number; skipped: number; score: number }
export type TestResult = { suite: string; passed: number; failed: number; skipped: number; duration_ms: number; failures?: TestFailure[] | null }
/**
 * One unresolved issue surfaced by the mission. Sum type with one
 * variant per producer event class.
 * 
 * Source events for each variant (documented for the inbox renderer):
 * 
 * * `OpenEscalation` — produced by
 * [`crate::mission_event::MissionEventKind::ArbiterDecided`]
 * with `bound = Some(_)`.
 * * `RecoveryAttempted` — produced by
 * [`crate::mission_event::MissionEventKind::RecoveryDecided`]
 * events that escalated or retried.
 * * `ContextBudgetTruncated` — produced by
 * [`crate::mission_event::MissionEventKind::ContextBudgetTruncated`]
 * (composer re-render path).
 * * `SubtaskScrubbed` — produced by an `ArbiterDecided` whose decision is
 * `Scrub`, such as quality-budget exhaustion.
 */
export type UnresolvedIssue = 
/**
 * Mission ended with an open arbiter escalation. The bound
 * identifies which envelope tripped; the summary is the
 * inbox-card preview text.
 */
{ kind: "open_escalation"; bound: AuthorityBound; summary: string } | 
/**
 * Recovery engine ran one or more times during the mission.
 * `class` is the wire name of the [`crate::recovery::types::FailureClass`]
 * (e.g. "missing_file", "command_error"); `action_taken` is
 * the wire name of the chosen [`crate::recovery::types::RecoveryAction`]
 * (e.g. "retry", "pause", "escalate"); `occurrences` is the
 * total count for this class across the mission.
 */
{ kind: "recovery_attempted"; class: string; action_taken: string; occurrences: number } | 
/**
 * Memory composer truncated the bundle for a worker because
 * its token budget was exceeded. `dropped_count` is the
 * number of notes that did not make it into the final
 * bundle; `worker_id` identifies which worker was affected.
 */
{ kind: "context_budget_truncated"; dropped_count: number; worker_id: string } | 
/**
 * A subtask was scrubbed after its quality budget was exhausted or its
 * audit became unusable. `task_index` and `reason` are the closing details.
 */
{ kind: "subtask_scrubbed"; task_index: number; reason: string }
/**
 * Closed set of supported worker vendors. Expanding requires a minor
 * schema-version bump; removing requires a major bump (see
 * [`SCHEMA_VERSION`]). `Aider` was removed in 2.0.
 */
export type Vendor = "claude" | "codex" | "gemini" | "antigravity" | "kiro" | "copilot" | "opencode" | "mock"
/**
 * Emitted to the frontend on each canonical worker event.
 * Transparent newtype so the wire payload is exactly the canonical
 * `event_schema::Event`.
 */
export type WorkerEvent = Event
/**
 * Worker identity record (§2). The orchestrator builds this at spawn
 * time and persists it; events reference the worker by `id`.
 */
export type WorkerInfo = { id: string; name: string; vendor: Vendor; cli_binary: string; cli_version: string | null; cwd: string; model: string | null; spawned_at: string; ended_at: string | null }
export type WorkerModelSwitchDto = { worker_id: string; model: string; detail: string }
/**
 * Phase 1 (decisions.md entry 6 — Single supervisor per mission,
 * permanent boundary). Roles a supervisor can request when asking
 * the orchestrator to spawn a worker. The team metaphor stops at
 * one level of supervision: requests for [`WorkerRole::Supervisor`]
 * are refused and surfaced as `boundary.sub_supervisor_refused`.
 * 
 * The current supervisor adapter cannot request another supervisor; its spawn
 * action names only a task index. This vocabulary is also used by handoff
 * records and retained event decoding.
 */
export type WorkerRole = "supervisor" | "employee"
/**
 * Lifecycle states a worker transitions through. Every adapter
 * announces `Idle` first, then advances the worker until it lands
 * on `Done`, `Failed`, or `Blocked`.
 */
export type WorkerState = "idle" | "planning" | "executing" | "blocked" | "reviewing" | "done" | "failed"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
