#!/usr/bin/env node

import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  copyLegalDistribution,
  legalDistributionFiles,
} from "./generate-license-notices.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const siteSource = path.join(repoRoot, "site");
const siteDist = path.join(siteSource, "dist");
const readmePath = path.join(repoRoot, "README.md");
const architecturePath = path.join(repoRoot, "ARCHITECTURE.md");
const llmsPath = path.join(repoRoot, "llms.txt");
const llmsFullPath = path.join(repoRoot, "llms-full.txt");
const webDemoPath = path.join(repoRoot, "app", "dist-webdemo");
const mediaPath = path.join(repoRoot, "docs", "media");
const iconPath = path.join(repoRoot, "app", "src-tauri", "icons", "icon.svg");

const args = new Set(process.argv.slice(2));
const writeLlms = args.has("--write-llms");
const checkOnly = args.has("--check");
const unknownArgs = [...args].filter(
  (arg) => arg !== "--write-llms" && arg !== "--check",
);
if (unknownArgs.length > 0) {
  throw new Error(`unknown argument(s): ${unknownArgs.join(", ")}`);
}

const [readme, architecture, siteHtml] = await Promise.all([
  readFile(readmePath, "utf8"),
  readFile(architecturePath, "utf8"),
  readFile(path.join(siteSource, "index.html"), "utf8"),
]);

function section(markdown, heading) {
  const marker = `## ${heading}`;
  const start = markdown.indexOf(marker);
  if (start === -1) throw new Error(`missing source section: ${marker}`);
  const next = markdown.indexOf("\n## ", start + marker.length);
  return markdown.slice(start, next === -1 ? markdown.length : next).trim();
}

function intro(markdown) {
  const firstSection = markdown.indexOf("\n## ");
  return markdown
    .slice(0, firstSection)
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      return (
        !/^<\/?(?:a|div|sub)\b/.test(trimmed) &&
        !/^<img\b/.test(trimmed) &&
        !/^!\[/.test(trimmed) &&
        !/^\[!\[/.test(trimmed) &&
        !/^\[Try the demo\]/.test(trimmed)
      );
    })
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function canonicalizeRepoLinks(markdown) {
  return markdown.replace(
    /\]\(\.\/([^\s)]+)\)/g,
    (_match, target) =>
      `](https://github.com/Kilbex/Vigla/blob/main/${target})`,
  );
}

const generatedHeader = [
  "<!-- Generated by scripts/build-site.mjs from README.md and ARCHITECTURE.md. -->",
  "<!-- Edit the source documents, then run: node scripts/build-site.mjs --write-llms -->",
].join("\n");

const llms = canonicalizeRepoLinks(`${generatedHeader}

${intro(readme)}

${section(readme, "How it works")}

${section(readme, "Vendor support")}

${section(readme, "Requirements")}

${section(readme, "Build a local DMG")}

${section(readme, "Known limitations")}

${section(readme, "Contributing")}

## Canonical resources

- Source: https://github.com/Kilbex/Vigla
- Browser replay: https://kilbex.github.io/Vigla/demo/
- Architecture: https://github.com/Kilbex/Vigla/blob/main/ARCHITECTURE.md
- Security: https://github.com/Kilbex/Vigla/blob/main/SECURITY.md
- Support: https://github.com/Kilbex/Vigla/blob/main/SUPPORT.md
- License: Apache-2.0
`);

const llmsFull = canonicalizeRepoLinks(`${generatedHeader}

# Vigla — full project context

Canonical source: https://github.com/Kilbex/Vigla

## README

${readme.trim()}

## Architecture reference

${architecture.trim()}
`);

if (writeLlms) {
  await Promise.all([
    writeFile(llmsPath, llms, "utf8"),
    writeFile(llmsFullPath, llmsFull, "utf8"),
  ]);
}

async function assertGeneratedFile(filePath, expected) {
  let actual;
  try {
    actual = await readFile(filePath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      throw new Error(`${path.basename(filePath)} is missing; run the --write-llms command`);
    }
    throw error;
  }
  if (actual !== expected) {
    throw new Error(`${path.basename(filePath)} is stale; run the --write-llms command`);
  }
}

await Promise.all([
  assertGeneratedFile(llmsPath, llms),
  assertGeneratedFile(llmsFullPath, llmsFull),
]);

function localReferences(html) {
  return [...html.matchAll(/(?:href|src|srcset)="(\.\/[^"\s]+)"/g)].map(
    (match) => match[1],
  );
}

async function assertPath(filePath, label) {
  try {
    await stat(filePath);
  } catch {
    throw new Error(`missing ${label}: ${path.relative(repoRoot, filePath)}`);
  }
}

async function assertSize(filePath, label, minimumBytes, maximumBytes) {
  const metadata = await stat(filePath);
  if (metadata.size < minimumBytes || metadata.size > maximumBytes) {
    throw new Error(
      `${label} is ${metadata.size} bytes; expected ${minimumBytes}–${maximumBytes} bytes`,
    );
  }
}

async function assertSameFile(actualPath, expectedPath, label) {
  const [actual, expected] = await Promise.all([
    readFile(actualPath),
    readFile(expectedPath),
  ]);
  if (!actual.equals(expected)) {
    throw new Error(`${label} does not match its canonical source`);
  }
}

for (const name of legalDistributionFiles) {
  await assertPath(path.join(repoRoot, name), name);
  await assertSameFile(
    path.join(webDemoPath, name),
    path.join(repoRoot, name),
    `web demo ${name}`,
  );
}

const retainedLicenseNames = await readdir(
  path.join(repoRoot, "third_party_licenses"),
);
for (const name of retainedLicenseNames) {
  await assertSameFile(
    path.join(webDemoPath, "third_party_licenses", name),
    path.join(repoRoot, "third_party_licenses", name),
    `web demo retained license ${name}`,
  );
}

for (const reference of localReferences(siteHtml)) {
  const withoutFragment = reference.split("#", 1)[0];
  if (withoutFragment === "./") continue;
  if (withoutFragment === "./demo/") {
    await assertPath(path.join(webDemoPath, "index.html"), "web demo build");
  } else if (withoutFragment === "./icon.svg") {
    await assertPath(iconPath, "site icon");
  } else if (withoutFragment === "./llms.txt") {
    await assertPath(llmsPath, "llms.txt");
  } else if (withoutFragment === "./llms-full.txt") {
    await assertPath(llmsFullPath, "llms-full.txt");
  } else if (withoutFragment.startsWith("./media/")) {
    await assertPath(
      path.join(mediaPath, withoutFragment.slice("./media/".length)),
      "site media",
    );
  } else {
    await assertPath(path.join(siteSource, withoutFragment.slice(2)), "site asset");
  }
}

for (const anchor of [...siteHtml.matchAll(/href="#([^"]+)"/g)].map((match) => match[1])) {
  if (!siteHtml.includes(`id="${anchor}"`)) {
    throw new Error(`site link targets missing anchor #${anchor}`);
  }
}

await Promise.all([
  assertSize(
    path.join(mediaPath, "vigla-demo.webp"),
    "animated replay",
    2 * 1024 * 1024,
    8 * 1024 * 1024,
  ),
  assertSize(
    path.join(mediaPath, "vigla-demo-poster.webp"),
    "hero replay poster",
    1,
    128 * 1024,
  ),
  assertSize(
    path.join(mediaPath, "mission-inbox.webp"),
    "landing evidence image",
    1,
    192 * 1024,
  ),
  assertSize(
    path.join(mediaPath, "roadmap-horizon.webp"),
    "roadmap illustration",
    32 * 1024,
    256 * 1024,
  ),
  assertSize(
    path.join(mediaPath, "social-preview.png"),
    "social preview",
    64 * 1024,
    768 * 1024,
  ),
]);

if (!siteHtml.includes('data-replay-src="./media/vigla-demo.webp"')) {
  throw new Error("site hero is missing the on-demand animated replay");
}

const retiredIdentityPattern = new RegExp(
  [["moon", "codemaster"].join(""), ["vo", "lary"].join("")].join("|"),
  "i",
);
if (retiredIdentityPattern.test(siteHtml)) {
  throw new Error("retired project identity found in site/index.html");
}

if (checkOnly) {
  process.stdout.write("site sources and generated AI context are current\n");
  process.exit(0);
}

await rm(siteDist, { recursive: true, force: true });
await mkdir(siteDist, { recursive: true });
await Promise.all([
  cp(path.join(siteSource, "index.html"), path.join(siteDist, "index.html")),
  cp(path.join(siteSource, "styles.css"), path.join(siteDist, "styles.css")),
  cp(path.join(siteSource, "site.js"), path.join(siteDist, "site.js")),
  cp(path.join(siteSource, "robots.txt"), path.join(siteDist, "robots.txt")),
  cp(path.join(siteSource, "sitemap.xml"), path.join(siteDist, "sitemap.xml")),
  cp(iconPath, path.join(siteDist, "icon.svg")),
  cp(mediaPath, path.join(siteDist, "media"), { recursive: true }),
  cp(webDemoPath, path.join(siteDist, "demo"), { recursive: true }),
  cp(llmsPath, path.join(siteDist, "llms.txt")),
  cp(llmsFullPath, path.join(siteDist, "llms-full.txt")),
  copyLegalDistribution(siteDist),
  writeFile(path.join(siteDist, ".nojekyll"), "", "utf8"),
]);

const files = await readdir(siteDist, { recursive: true });
process.stdout.write(`built site/dist (${files.length} entries)\n`);
