import { memo } from "react";
import type { Vendor, WorkerState } from "../bindings";
import { getAvatarProfile } from "./avatar";
import type { VendorHue } from "./avatar";
import claudeIcon from "../assets/avatars/claude-icon.svg";
import codexIcon from "../assets/avatars/codex-icon.svg";
import geminiIcon from "../assets/avatars/gemini-icon.svg";

interface WorkerAvatarProps {
  vendor: Vendor;
  state: WorkerState;
}

/// Per-vendor pixel-art icon sprite. Sprites are 14×14 logical pixels
/// rendered at 2× via CSS to fit the 28×28 worker-avatar slot. Sprites
/// live under `app/src/assets/avatars/` and are generated by
/// `docs/character-designs/generate.py` (source of truth).
const PORTRAIT_ICONS: Partial<Record<VendorHue, string>> = {
  claude: claudeIcon,
  codex: codexIcon,
  gemini: geminiIcon,
};

/// Replaceable avatar slot for a worker station. Pure projection of
/// `(vendor, state)` via `getAvatarProfile`. The DOM shape is identical
/// for every input — only inner content and class names change — so
/// vendor/state transitions never cause layout shift inside the station
/// header. Two avatar kinds coexist:
///   - portrait: hand-pixelled icon (claude / codex / gemini)
///   - placeholder: letter glyph (opencode / mock / unknown)
function WorkerAvatarInner({ vendor, state }: WorkerAvatarProps) {
  const { avatarType, vendorGlyph, roleBadge, stateOverlay, animationProfile, label } =
    getAvatarProfile(vendor, state);

  const className = [
    "worker-avatar",
    `worker-avatar--type-${avatarType}`,
    `worker-avatar--vendor-${vendorGlyph.hue}`,
    `worker-avatar--state-${stateOverlay}`,
    `worker-avatar--anim-${animationProfile}`,
  ].join(" ");

  const iconSrc = avatarType === "portrait" ? PORTRAIT_ICONS[vendorGlyph.hue] : undefined;

  return (
    <span
      className={className}
      role="img"
      aria-label={label}
      data-testid="worker-avatar"
      data-vendor={vendorGlyph.hue}
      data-state={stateOverlay}
      data-role={roleBadge}
      data-avatar-type={avatarType}
    >
      <span className="worker-avatar__ring" aria-hidden />
      {iconSrc ? (
        <img
          className="worker-avatar__sprite"
          src={iconSrc}
          alt=""
          aria-hidden
          draggable={false}
        />
      ) : (
        <span className="worker-avatar__glyph" aria-hidden>
          {vendorGlyph.letter}
        </span>
      )}
      <span className="worker-avatar__role-band" aria-hidden />
      <span className="worker-avatar__overlay" aria-hidden />
    </span>
  );
}

export const WorkerAvatar = memo(WorkerAvatarInner);
export default WorkerAvatar;
